#!/usr/bin/env bash

set -ex

SERVER=rtmp://stream.younow.com/liveapp
KEY=42864489_1_69336ceecb8a368133eab29e9216efb8

ffmpeg \
        -i `youtube-dl -f best -g https://www.youtube.com/watch?v=GSb6eDzAWtE` \
        -i banana.gif -filter_complex "[0][1]overlay=0:10" \
	-vcodec libx264 -pix_fmt yuv420p -preset medium -r 30 -g 60 -b:v 1000k \
        -f flv "$SERVER/$KEY"
